#!/bin/sh
# Copyright (c) 2021 Matthew Nelson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
TOOL="$1"; shift 1

readonly DIR_SCRIPT=$( cd "$( dirname "$0" )" >/dev/null && pwd )

if [ -z "${TOOL}" ] || [ ! -d "$DIR_SCRIPT/tools/${TOOL}" ]; then
  echo "Unknown tool: '${TOOL}'"
  exit 1
fi

args="$*"
args="${args%"${args##*[![:space:]]}"}"

cd "$DIR_SCRIPT" || exit 3

./gradlew --quiet ":tools:${TOOL}:jvmRun" --args="$args"
