[versions]
android = "7.3.1"
binaryCompat = "0.13.0"
configuration = "0.1.0-beta02"
cryptoHash = "0.2.0"
encoding = "1.2.1"
gradleVersions = "0.46.0"
kotlin = "1.8.10"
kotlinTime = "0.4.0"
kotlinCli = "0.3.5"
npmPublish = "2.1.2"
okio = "3.3.0"
publish = "0.24.0"
valueClazz = "0.1.0"

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "android" }
gradle-kmp-configuration = { module = "io.matthewnelson:gradle-kmp-configuration-plugin", version.ref = "configuration" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish" }

# 3.0.0+ change to >>>           dev.petuska:npm-publish-gradle-plugin
gradle-npm-publish = { module = "dev.petuska:npm-publish", version.ref = "npmPublish" }

# Tests/tooling
encoding-base16 = { module = "io.matthewnelson.kotlin-components:encoding-base16", version.ref = "encoding" }
encoding-base64 = { module = "io.matthewnelson.kotlin-components:encoding-base64", version.ref = "encoding" }
kotlincrypto-hash-sha2 = { module = "org.kotlincrypto.hash:sha2", version.ref = "cryptoHash" }
kotlin-cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version.ref = "kotlinCli" }
kotlin-time = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinTime" }
okio-okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakeFileSystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
okio-node = { module = "com.squareup.okio:okio-nodefilesystem", version.ref = "okio" }
valueClazz = { module = "io.matthewnelson.kotlin-components:value-clazz", version.ref = "valueClazz" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android" }
binaryCompat = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompat" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersions" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
