[package]
name = "kmp-tor"
version = "46.9.0+0.4.6.9"
authors = [ "Matthew Nelson <developer@matthewnelson.io>" ]
license = "Apache 2.0"
homepage = "https://github.com/05nelsonm/kmp-tor"
repository = "https://github.com/05nelsonm/kmp-tor"
description = "JNI bindings for kmp-tor"
keywords = [ "tor", "kmp-tor" ]
readme = "README.md"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.19.0"
libtor-sys = { version = "46.9.0+0.4.6.9", features = ["vendored-openssl"] }

[lib]
name = "KmpTor"
crate_type = [ "cdylib" ]
test = false
bench = false
